name: BUILDER

on:
  push:
    branches:
      - 'master'

jobs:

  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Configure docker"
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name local-build
          docker buildx use local-build

      - name: "Build and push image"
        run: |
          export VERSION=$(cat VERSION)
          
          export IMAGE=ghcr.io/${{ github.repository }}:$VERSION
          export PLATFORMS=linux/amd64,linux/arm64

          docker buildx b --progress plain --provenance false --platform $PLATFORMS --build-arg VERSION=$VERSION -t $IMAGE --push .
